name: Run Pytest with Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest with Coverage
        timeout-minutes: 5
        run: pytest --cov=./notion_to_markdown --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: atb00ker/notion-to-markdown
